### ISSUE TITLE
/v1/user/auth?token=xxxx 提示  "errcode": -1,   "errmsg": "token absent"

### ISSUE THREAD

**Issue by Liberxue** [khlipeng/beego_api#1]
/v1/user/auth?token=xxxx 提示  "errcode": -1,   "errmsg": "token absent"

请问大神正确效验token的姿势啊  我是go新手帮忙指教 ☆⌒(*＾-゜)v THX!!

**Comment by khlipeng** [comment]
token 携带在 header 中

`Authorization`:`Bearer  Token`

**Comment by Liberxue** [comment]
![image](https://user-images.githubusercontent.com/5831248/29550741-f46ed24a-8741-11e7-9f01-c70ebcac0481.png)
大神 我在 header 里面写了token的key 也是
```
{
  "errcode": -1,
  "errmsg": "token absent"
}
```

方便可以来一个 http的demo 吗 多谢 大神

**Comment by khlipeng** [comment]
[
<img width="457" alt="1233333" src="https://user-images.githubusercontent.com/8134283/29550846-96835e16-8742-11e7-9eef-e9e3b9ecd208.png">
](url)

Authorization:Bearer Token

明白了吗？

**Comment by Liberxue** [comment]
懂了 多谢 大神 第一次用token 长见识了 😆 多谢 多谢  我学习 学习
